global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  metrics:
    address: :8082
  imaps:
    address: :993
  smtps:
    address: :465
log:
  level: INFO
  filePath: /etc/traefik/log/traefik.log
accessLog:
  filePath: /etc/traefik/log/access.log
  format: json
api:
  insecure: false
  dashboard: true
certificatesResolvers:
  leresolver:
    acme:
      email: pierrelouisguhur@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
ping: {}
providers:
  docker: {}
metrics:
  prometheus:
    addRoutersLabels: true
    entryPoint: metrics
experimental:
  devPlugin:
    goPath: /home/${USER}/go
    moduleName: github.com/tomMoulard/fail2ban

