version: '3.8'

services:
  
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - $DATA_DIR:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - $LOG_DIR:/www/logs
    environment:
    - VIRTUAL_HOST=freescout.${DOMAIN}
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=freescout.${DOMAIN}
    - LETSENCRYPT_EMAIL=${EMAIL}

    - CONTAINER_NAME=freescout-app
    
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=freescout

    - SITE_URL=https://freescout.${DOMAIN}
    - ADMIN_EMAIL=$EMAIL
    - ADMIN_PASS=freescout
    - ENABLE_SSL_PROXY=TRUE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=$TIMEZONE
    - PUID=$PUID
    - PGID=$PGID
    networks:
      - lan
      - traefik_network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.freescout.entrypoints=web,websecure"
      - "traefik.http.routers.freescout.rule=Host(`freescout.${DOMAIN}`)"
      - "traefik.http.services.freescout.loadbalancer.server.port=80"
      - "traefik.http.routers.freescout.tls=true"
      - "traefik.http.routers.freescout.tls.certresolver=leresolver"

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - CONTAINER_NAME=freescout-db
    networks:
      - lan
    restart: always

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - lan
    restart: always


networks:
  lan:
  traefik_network:
    external: true

